spring.application.name=SpringBoot



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true



spring.datasource.url=jdbc:mysql://localhost:3306/loginform
spring.datasource.username=loginapp
spring.datasource.password=LoginApp@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



#CREATE DATABASE loginform;
#show tables;
#select * from user_details;
#DELETE FROM user_details;
#DELETE FROM user_details where user_id = 2 ;
#DROP DATABASE loginform;
